server:
  port: 18080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**,/api/login,/api/register,/api/token/refresh,/api/logout
    nacos:
      discovery:
        server-addr: common-nacos-dev.magestack.cn:8848
        namespace: 11d3f062-8d0c-4fd4-86ac-4cca968f589f
